export const quotes = [
  "Work until your bank account looks like a phone number.",
  "I love deadlines. I like the whooshing sound they make as they fly by.",
  "Hard work never killed anybody, but why take a chance?",
  "The best way to appreciate your job is to imagine yourself without one.",
  "If A equals success, then the formula is A equals X plus Y and Z, with X being work, Y play, and Z keeping your mouth shut.",
  "By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The only place success comes before work is in the dictionary.",
  "It takes less time to do a thing right, than it does to explain why you did it wrong.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "Don't count the days, make the days count.",
  "A diamond is merely a lump of coal that did well under pressure.",
  "If you think your boss is stupid, remember: you wouldn't have a job if he was any smarter.",
  "Even if you are on the right track, you will get run over if you just sit there.",
  "I always give 100% at Work: 10% Monday, 23% Tuesday, 40% Wednesday, 22% Thursday, and 5% Friday.",
  "I like work: it fascinates me. I can sit and look at it for hours.",
  "The elevator to success is out of order. You'll have to use the stairs, one step at a time.",
  "Whether you think you can, or you think you can't - you're right.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Creativity is intelligence having fun.",
  "Do what you can, with what you have, where you are.",
  "You miss 100% of the shots you don't take.",
  "I attribute my success to this: I never gave or took any excuse.",
  "Everything you've ever wanted is on the other side of fear.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "The mind is everything. What you think you become.",
  "Eighty percent of success is showing up.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Winning isn't everything, but wanting to win is.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Every child is an artist. The problem is how to remain an artist once he grows up.",
  "Either you run the day, or the day runs you.",
  "The best revenge is massive success.",
  "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily.",
  "Life shrinks or expands in proportion to one's courage.",
  "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "Certain things catch your eye, but pursue only those that capture the heart.",
  "Believe you can and you're halfway there.",
  "Everything has beauty, but not everyone can see.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "When I let go of what I am, I become what I might be.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "Happiness is not something readymade. It comes from your own actions.",
  "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.",
  "Too many of us are not living our dreams because we are living our fears.",
  "Whatever the mind of man can conceive and believe, it can achieve."
];
